start =
    expression

whitespace = 
    " "
    / "\t"
    / "\n"
    / "\r"

expression =
    x:atom
        {return x;}
    / whitespace* "(" whitespace* x:wordlist whitespace* ")" whitespace* 
        {return x;}

validchar
    = [0-9a-zA-Z_?!+\-=@#$%^&*/.]

atom =
    chars:validchar+
        { return chars.join(""); }


wordlist =
    w:expression rest:space_and_word*
    { return [w].concat(rest); }

space_and_word =
    whitespace+ w:expression
    {return w; }

word =
    w:atom

